export const LOAD_JOBS_SUCCESS = "LOAD_JOBS_SUCCESS";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";


export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";


export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

