# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn test
    - run: yarn build
    - name: Upload Frontend
      uses: appleboy/scp-action@v0.0.7         
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./build/*"
        target: "/tmp/deploy/frontend"
    - name: Upload Backend
      uses: appleboy/scp-action@v0.0.7         
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "server/server.js,server/package.json"
        target: "/tmp/deploy/backend"
    - name: Reload Backend
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: cd /tmp/deploy/backend/ && cp server/* . && sudo npm install && sudo pm2 restart server
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: build
      env:
        CI: true
